apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache-php
  name: apache-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  strategy: {}
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      terminationGracePeriodSeconds: 1200 # 20 minutes
      containers:
        - image: aubm/apache-php-graceful-shutdown-demo:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 80
              path: "/?health=1"
          readinessProbe:
            httpGet:
              port: 80
              path: "/?health=1"
          lifecycle:
            preStop:
              exec:
                command: ["/opt/shutdown.sh"]
          name: apache-php
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-php
  name: apache-php
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache-php
  type: LoadBalancer
